// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace USAID.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources2 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources2() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("USAID.Resx.AppResources2", typeof(AppResources2).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string ApplicationHeading {
            get {
                return ResourceManager.GetString("ApplicationHeading", resourceCulture);
            }
        }
        
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        internal static string SpeakButton {
            get {
                return ResourceManager.GetString("SpeakButton", resourceCulture);
            }
        }
        
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        internal static string WorkingText {
            get {
                return ResourceManager.GetString("WorkingText", resourceCulture);
            }
        }
        
        internal static string NoInternetText {
            get {
                return ResourceManager.GetString("NoInternetText", resourceCulture);
            }
        }
        
        internal static string HomeMenuText {
            get {
                return ResourceManager.GetString("HomeMenuText", resourceCulture);
            }
        }
        
        internal static string SitesMenuText {
            get {
                return ResourceManager.GetString("SitesMenuText", resourceCulture);
            }
        }
        
        internal static string AboutMenuText {
            get {
                return ResourceManager.GetString("AboutMenuText", resourceCulture);
            }
        }
        
        internal static string LogOutMenuText {
            get {
                return ResourceManager.GetString("LogOutMenuText", resourceCulture);
            }
        }
        
        internal static string DetailsText {
            get {
                return ResourceManager.GetString("DetailsText", resourceCulture);
            }
        }
        
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        internal static string WelcomeLabel {
            get {
                return ResourceManager.GetString("WelcomeLabel", resourceCulture);
            }
        }
        
        internal static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        internal static string PassowrdHint {
            get {
                return ResourceManager.GetString("PassowrdHint", resourceCulture);
            }
        }
        
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        internal static string ToCreatePofileLabel {
            get {
                return ResourceManager.GetString("ToCreatePofileLabel", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordLink {
            get {
                return ResourceManager.GetString("ForgotPasswordLink", resourceCulture);
            }
        }
        
        internal static string LoginErrorText {
            get {
                return ResourceManager.GetString("LoginErrorText", resourceCulture);
            }
        }
        
        internal static string LandingPageTitle {
            get {
                return ResourceManager.GetString("LandingPageTitle", resourceCulture);
            }
        }
        
        internal static string DownloadText {
            get {
                return ResourceManager.GetString("DownloadText", resourceCulture);
            }
        }
        
        internal static string LastInformationText {
            get {
                return ResourceManager.GetString("LastInformationText", resourceCulture);
            }
        }
        
        internal static string DownloadButtonText {
            get {
                return ResourceManager.GetString("DownloadButtonText", resourceCulture);
            }
        }
        
        internal static string NoDownloadText {
            get {
                return ResourceManager.GetString("NoDownloadText", resourceCulture);
            }
        }
        
        internal static string SitesPageTitle {
            get {
                return ResourceManager.GetString("SitesPageTitle", resourceCulture);
            }
        }
        
        internal static string NoSitesText {
            get {
                return ResourceManager.GetString("NoSitesText", resourceCulture);
            }
        }
        
        internal static string SitePageTitle {
            get {
                return ResourceManager.GetString("SitePageTitle", resourceCulture);
            }
        }
        
        internal static string SiteInformationLabel {
            get {
                return ResourceManager.GetString("SiteInformationLabel", resourceCulture);
            }
        }
        
        internal static string SiteNameLabel {
            get {
                return ResourceManager.GetString("SiteNameLabel", resourceCulture);
            }
        }
        
        internal static string CountryNameLabel {
            get {
                return ResourceManager.GetString("CountryNameLabel", resourceCulture);
            }
        }
        
        internal static string SiteTypeLabel {
            get {
                return ResourceManager.GetString("SiteTypeLabel", resourceCulture);
            }
        }
        
        internal static string RegionLabel {
            get {
                return ResourceManager.GetString("RegionLabel", resourceCulture);
            }
        }
        
        internal static string DistrictLabel {
            get {
                return ResourceManager.GetString("DistrictLabel", resourceCulture);
            }
        }
        
        internal static string SubDistrictLabel {
            get {
                return ResourceManager.GetString("SubDistrictLabel", resourceCulture);
            }
        }
        
        internal static string CityTownVillageLabel {
            get {
                return ResourceManager.GetString("CityTownVillageLabel", resourceCulture);
            }
        }
        
        internal static string PartnerLabel {
            get {
                return ResourceManager.GetString("PartnerLabel", resourceCulture);
            }
        }
        
        internal static string FundingTypeLabel {
            get {
                return ResourceManager.GetString("FundingTypeLabel", resourceCulture);
            }
        }
        
        internal static string LongitudeLabel {
            get {
                return ResourceManager.GetString("LongitudeLabel", resourceCulture);
            }
        }
        
        internal static string LattitudeLabel {
            get {
                return ResourceManager.GetString("LattitudeLabel", resourceCulture);
            }
        }
        
        internal static string QIIndexScoreLabel {
            get {
                return ResourceManager.GetString("QIIndexScoreLabel", resourceCulture);
            }
        }
        
        internal static string RuralUrbanLabel {
            get {
                return ResourceManager.GetString("RuralUrbanLabel", resourceCulture);
            }
        }
        
        internal static string OtherKeyInformationLabel {
            get {
                return ResourceManager.GetString("OtherKeyInformationLabel", resourceCulture);
            }
        }
        
        internal static string AboutUsPageTitle {
            get {
                return ResourceManager.GetString("AboutUsPageTitle", resourceCulture);
            }
        }
        
        internal static string AboutUsDetailText {
            get {
                return ResourceManager.GetString("AboutUsDetailText", resourceCulture);
            }
        }
        
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        internal static string IndicatorsPageTitle {
            get {
                return ResourceManager.GetString("IndicatorsPageTitle", resourceCulture);
            }
        }
        
        internal static string ActivityDetailPageTitle {
            get {
                return ResourceManager.GetString("ActivityDetailPageTitle", resourceCulture);
            }
        }
        
        internal static string ActivityInformationLabel {
            get {
                return ResourceManager.GetString("ActivityInformationLabel", resourceCulture);
            }
        }
        
        internal static string OrganizationLabel {
            get {
                return ResourceManager.GetString("OrganizationLabel", resourceCulture);
            }
        }
        
        internal static string ProjectLabel {
            get {
                return ResourceManager.GetString("ProjectLabel", resourceCulture);
            }
        }
        
        internal static string ActivityNameLabel {
            get {
                return ResourceManager.GetString("ActivityNameLabel", resourceCulture);
            }
        }
        
        internal static string CountryLabel {
            get {
                return ResourceManager.GetString("CountryLabel", resourceCulture);
            }
        }
        
        internal static string ActivityManagerLabel {
            get {
                return ResourceManager.GetString("ActivityManagerLabel", resourceCulture);
            }
        }
    }
}
