//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Globalization.Admin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IID.BusinessLayer.Globalization.Admin.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Site.
        /// </summary>
        public static string AddSite {
            get {
                return ResourceManager.GetString("AddSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Dashboard.
        /// </summary>
        public static string CountryDashboard {
            get {
                return ResourceManager.GetString("CountryDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Activity Funder.
        /// </summary>
        public static string FieldIDActivityFunder {
            get {
                return ResourceManager.GetString("FieldIDActivityFunder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Activity Technical Area.
        /// </summary>
        public static string FieldIDActivityTechnicalArea {
            get {
                return ResourceManager.GetString("FieldIDActivityTechnicalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Activity Technical Area Sub Type.
        /// </summary>
        public static string FieldIDActivityTechnicalAreaSubType {
            get {
                return ResourceManager.GetString("FieldIDActivityTechnicalAreaSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Indicator Group.
        /// </summary>
        public static string FieldIDIndicatorGroup {
            get {
                return ResourceManager.GetString("FieldIDIndicatorGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Indicator Sampling.
        /// </summary>
        public static string FieldIDIndicatorSampling {
            get {
                return ResourceManager.GetString("FieldIDIndicatorSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Indicator Report Class.
        /// </summary>
        public static string FieldIDReportClass {
            get {
                return ResourceManager.GetString("FieldIDReportClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Site Funding Type.
        /// </summary>
        public static string FieldIDSiteFundingType {
            get {
                return ResourceManager.GetString("FieldIDSiteFundingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Dropdowns: Site Population Density.
        /// </summary>
        public static string FieldIDSitePopulationDensity {
            get {
                return ResourceManager.GetString("FieldIDSitePopulationDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Requests.
        /// </summary>
        public static string ManageRequests {
            get {
                return ResourceManager.GetString("ManageRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Statistics.
        /// </summary>
        public static string UserStatistics {
            get {
                return ResourceManager.GetString("UserStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string ViewRequests {
            get {
                return ResourceManager.GetString("ViewRequests", resourceCulture);
            }
        }
    }
}
