//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entity : DbContext
    {
        public Entity()
            : base("name=Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_activity> t_activity { get; set; }
        public virtual DbSet<t_administrative_division> t_administrative_division { get; set; }
        public virtual DbSet<t_aim> t_aim { get; set; }
        public virtual DbSet<t_announcement> t_announcement { get; set; }
        public virtual DbSet<t_country> t_country { get; set; }
        public virtual DbSet<t_date> t_date { get; set; }
        public virtual DbSet<t_fieldid> t_fieldid { get; set; }
        public virtual DbSet<t_indicator> t_indicator { get; set; }
        public virtual DbSet<t_indicator_age_range> t_indicator_age_range { get; set; }
        public virtual DbSet<t_language> t_language { get; set; }
        public virtual DbSet<t_note> t_note { get; set; }
        public virtual DbSet<t_observation> t_observation { get; set; }
        public virtual DbSet<t_observation_attachment> t_observation_attachment { get; set; }
        public virtual DbSet<t_observation_change> t_observation_change { get; set; }
        public virtual DbSet<t_observation_comment> t_observation_comment { get; set; }
        public virtual DbSet<t_organization> t_organization { get; set; }
        public virtual DbSet<t_page_control_translation> t_page_control_translation { get; set; }
        public virtual DbSet<t_project> t_project { get; set; }
        public virtual DbSet<t_site> t_site { get; set; }
        public virtual DbSet<t_translation> t_translation { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<t_user_access> t_user_access { get; set; }
        public virtual DbSet<t_user_favorite_chart> t_user_favorite_chart { get; set; }
        public virtual DbSet<t_user_role> t_user_role { get; set; }
        public virtual DbSet<t_user_status> t_user_status { get; set; }
        public virtual DbSet<v_site> v_site { get; set; }
        public virtual DbSet<v_administrative_division> v_administrative_division { get; set; }
        public virtual DbSet<t_observation_entry> t_observation_entry { get; set; }
        public virtual DbSet<t_sex> t_sex { get; set; }
        public virtual DbSet<t_activity_site> t_activity_site { get; set; }
        public virtual DbSet<t_observation_entry_change_history> t_observation_entry_change_history { get; set; }
        public virtual DbSet<v_user> v_user { get; set; }
        public virtual DbSet<v_user_access> v_user_access { get; set; }
        public virtual DbSet<t_color> t_color { get; set; }
        public virtual DbSet<t_chart_acceptable_number_runs> t_chart_acceptable_number_runs { get; set; }
        public virtual DbSet<v_observation_date_period> v_observation_date_period { get; set; }
    
        public virtual ObjectResult<p_api_attachment_get_Result> p_api_attachment_get(string userid, Nullable<int> language_id)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_attachment_get_Result>("p_api_attachment_get", useridParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_change_get_Result> p_api_change_get(string userid, Nullable<int> language_id)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_change_get_Result>("p_api_change_get", useridParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_fieldid_get_Result> p_api_fieldid_get(string fieldid, string parentfieldid, string user_guid)
        {
            var fieldidParameter = fieldid != null ?
                new ObjectParameter("fieldid", fieldid) :
                new ObjectParameter("fieldid", typeof(string));
    
            var parentfieldidParameter = parentfieldid != null ?
                new ObjectParameter("parentfieldid", parentfieldid) :
                new ObjectParameter("parentfieldid", typeof(string));
    
            var user_guidParameter = user_guid != null ?
                new ObjectParameter("user_guid", user_guid) :
                new ObjectParameter("user_guid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_fieldid_get_Result>("p_api_fieldid_get", fieldidParameter, parentfieldidParameter, user_guidParameter);
        }
    
        public virtual ObjectResult<p_api_indicator_get_Result> p_api_indicator_get(string userid, Nullable<int> language_id)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_indicator_get_Result>("p_api_indicator_get", useridParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_observation_get_Result> p_api_observation_get(string userid, Nullable<int> language_id)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_observation_get_Result>("p_api_observation_get", useridParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_observationcomment_get_Result> p_api_observationcomment_get(string userid, Nullable<int> language_id)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_observationcomment_get_Result>("p_api_observationcomment_get", useridParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_site_get_Result> p_api_site_get(string userid, Nullable<int> language_id)
        {
            var useridParameter = userid != null ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_site_get_Result>("p_api_site_get", useridParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_get_home_objects_Result> p_get_home_objects(Nullable<int> user_id, Nullable<int> language_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_home_objects_Result>("p_get_home_objects", user_idParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_get_indicator_site_observations_Result> p_get_indicator_site_observations(Nullable<int> indicator_id, Nullable<int> site_id)
        {
            var indicator_idParameter = indicator_id.HasValue ?
                new ObjectParameter("indicator_id", indicator_id) :
                new ObjectParameter("indicator_id", typeof(int));
    
            var site_idParameter = site_id.HasValue ?
                new ObjectParameter("site_id", site_id) :
                new ObjectParameter("site_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_indicator_site_observations_Result>("p_get_indicator_site_observations", indicator_idParameter, site_idParameter);
        }
    
        public virtual ObjectResult<p_get_projects_Result> p_get_projects(Nullable<int> user_id, Nullable<int> language_id)
        {
            var user_idParameter = user_id.HasValue ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(int));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_projects_Result>("p_get_projects", user_idParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_get_latest_date_period_Result> p_get_latest_date_period(Nullable<System.DateTime> date, string frequency)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var frequencyParameter = frequency != null ?
                new ObjectParameter("frequency", frequency) :
                new ObjectParameter("frequency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_latest_date_period_Result>("p_get_latest_date_period", dateParameter, frequencyParameter);
        }
    
        public virtual int p_get_observations(Nullable<int> indicator_id, Nullable<int> site_id, Nullable<System.DateTime> observation_date)
        {
            var indicator_idParameter = indicator_id.HasValue ?
                new ObjectParameter("indicator_id", indicator_id) :
                new ObjectParameter("indicator_id", typeof(int));
    
            var site_idParameter = site_id.HasValue ?
                new ObjectParameter("site_id", site_id) :
                new ObjectParameter("site_id", typeof(int));
    
            var observation_dateParameter = observation_date.HasValue ?
                new ObjectParameter("observation_date", observation_date) :
                new ObjectParameter("observation_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_get_observations", indicator_idParameter, site_idParameter, observation_dateParameter);
        }
    
        public virtual int p_get_period_end_date(Nullable<System.DateTime> begin_date, string frequency, ObjectParameter end_date)
        {
            var begin_dateParameter = begin_date.HasValue ?
                new ObjectParameter("begin_date", begin_date) :
                new ObjectParameter("begin_date", typeof(System.DateTime));
    
            var frequencyParameter = frequency != null ?
                new ObjectParameter("frequency", frequency) :
                new ObjectParameter("frequency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_get_period_end_date", begin_dateParameter, frequencyParameter, end_date);
        }
    
        public virtual ObjectResult<p_get_date_periods_Result> p_get_date_periods(Nullable<System.DateTime> date, string frequency, Nullable<int> periods)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var frequencyParameter = frequency != null ?
                new ObjectParameter("frequency", frequency) :
                new ObjectParameter("frequency", typeof(string));
    
            var periodsParameter = periods.HasValue ?
                new ObjectParameter("periods", periods) :
                new ObjectParameter("periods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_date_periods_Result>("p_get_date_periods", dateParameter, frequencyParameter, periodsParameter);
        }
    
        public virtual ObjectResult<p_get_observation_date_periods_Result> p_get_observation_date_periods(Nullable<int> indicator_id, Nullable<int> site_id, Nullable<System.DateTime> date, Nullable<int> periods)
        {
            var indicator_idParameter = indicator_id.HasValue ?
                new ObjectParameter("indicator_id", indicator_id) :
                new ObjectParameter("indicator_id", typeof(int));
    
            var site_idParameter = site_id.HasValue ?
                new ObjectParameter("site_id", site_id) :
                new ObjectParameter("site_id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var periodsParameter = periods.HasValue ?
                new ObjectParameter("periods", periods) :
                new ObjectParameter("periods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_get_observation_date_periods_Result>("p_get_observation_date_periods", indicator_idParameter, site_idParameter, dateParameter, periodsParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_Result> p_api_get_mydata(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_Result>("p_api_get_mydata", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_activities_Result> p_api_get_mydata_activities(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_activities_Result>("p_api_get_mydata_activities", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_indicator_age_periods_Result> p_api_get_mydata_indicator_age_periods(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_indicator_age_periods_Result>("p_api_get_mydata_indicator_age_periods", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_indicators_Result> p_api_get_mydata_indicators(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_indicators_Result>("p_api_get_mydata_indicators", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_observation_attachments_Result> p_api_get_mydata_observation_attachments(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_observation_attachments_Result>("p_api_get_mydata_observation_attachments", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_observation_changes_Result> p_api_get_mydata_observation_changes(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_observation_changes_Result>("p_api_get_mydata_observation_changes", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_observation_comments_Result> p_api_get_mydata_observation_comments(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_observation_comments_Result>("p_api_get_mydata_observation_comments", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_observation_entries_Result> p_api_get_mydata_observation_entries(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_observation_entries_Result>("p_api_get_mydata_observation_entries", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_observations_Result> p_api_get_mydata_observations(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_observations_Result>("p_api_get_mydata_observations", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_site_indicators_Result> p_api_get_mydata_site_indicators(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_site_indicators_Result>("p_api_get_mydata_site_indicators", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_sites_Result> p_api_get_mydata_sites(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_sites_Result>("p_api_get_mydata_sites", user_emailParameter, language_idParameter);
        }
    
        public virtual ObjectResult<p_api_put_observation_Result> p_api_put_observation(Nullable<int> observation_id, Nullable<int> indicator_id, Nullable<int> site_id, Nullable<System.DateTime> begin_date, Nullable<System.DateTime> end_date, string user_email)
        {
            var observation_idParameter = observation_id.HasValue ?
                new ObjectParameter("observation_id", observation_id) :
                new ObjectParameter("observation_id", typeof(int));
    
            var indicator_idParameter = indicator_id.HasValue ?
                new ObjectParameter("indicator_id", indicator_id) :
                new ObjectParameter("indicator_id", typeof(int));
    
            var site_idParameter = site_id.HasValue ?
                new ObjectParameter("site_id", site_id) :
                new ObjectParameter("site_id", typeof(int));
    
            var begin_dateParameter = begin_date.HasValue ?
                new ObjectParameter("begin_date", begin_date) :
                new ObjectParameter("begin_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_put_observation_Result>("p_api_put_observation", observation_idParameter, indicator_idParameter, site_idParameter, begin_dateParameter, end_dateParameter, user_emailParameter);
        }
    
        [DbFunction("Entity", "f_get_date_periods")]
        public virtual IQueryable<f_get_date_periods_Result> f_get_date_periods(Nullable<System.DateTime> date, string frequency, Nullable<int> periods)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var frequencyParameter = frequency != null ?
                new ObjectParameter("frequency", frequency) :
                new ObjectParameter("frequency", typeof(string));
    
            var periodsParameter = periods.HasValue ?
                new ObjectParameter("periods", periods) :
                new ObjectParameter("periods", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_get_date_periods_Result>("[Entity].[f_get_date_periods](@date, @frequency, @periods)", dateParameter, frequencyParameter, periodsParameter);
        }
    
        [DbFunction("Entity", "f_get_latest_date_period")]
        public virtual IQueryable<f_get_latest_date_period_Result> f_get_latest_date_period(Nullable<System.DateTime> date, string frequency)
        {
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var frequencyParameter = frequency != null ?
                new ObjectParameter("frequency", frequency) :
                new ObjectParameter("frequency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_get_latest_date_period_Result>("[Entity].[f_get_latest_date_period](@date, @frequency)", dateParameter, frequencyParameter);
        }
    
        public virtual int p_util_generate_triggers(string schemaname, string tablename, Nullable<bool> generateScriptOnly, Nullable<bool> forceDropAuditTable, Nullable<bool> ignoreExistingColumnMismatch)
        {
            var schemanameParameter = schemaname != null ?
                new ObjectParameter("Schemaname", schemaname) :
                new ObjectParameter("Schemaname", typeof(string));
    
            var tablenameParameter = tablename != null ?
                new ObjectParameter("Tablename", tablename) :
                new ObjectParameter("Tablename", typeof(string));
    
            var generateScriptOnlyParameter = generateScriptOnly.HasValue ?
                new ObjectParameter("GenerateScriptOnly", generateScriptOnly) :
                new ObjectParameter("GenerateScriptOnly", typeof(bool));
    
            var forceDropAuditTableParameter = forceDropAuditTable.HasValue ?
                new ObjectParameter("ForceDropAuditTable", forceDropAuditTable) :
                new ObjectParameter("ForceDropAuditTable", typeof(bool));
    
            var ignoreExistingColumnMismatchParameter = ignoreExistingColumnMismatch.HasValue ?
                new ObjectParameter("IgnoreExistingColumnMismatch", ignoreExistingColumnMismatch) :
                new ObjectParameter("IgnoreExistingColumnMismatch", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_util_generate_triggers", schemanameParameter, tablenameParameter, generateScriptOnlyParameter, forceDropAuditTableParameter, ignoreExistingColumnMismatchParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<p_api_update_observation_comment_Result> p_api_update_observation_comment(Nullable<int> observation_comment_id, Nullable<int> observation_id, string comment, string user_email)
        {
            var observation_comment_idParameter = observation_comment_id.HasValue ?
                new ObjectParameter("observation_comment_id", observation_comment_id) :
                new ObjectParameter("observation_comment_id", typeof(int));
    
            var observation_idParameter = observation_id.HasValue ?
                new ObjectParameter("observation_id", observation_id) :
                new ObjectParameter("observation_id", typeof(int));
    
            var commentParameter = comment != null ?
                new ObjectParameter("comment", comment) :
                new ObjectParameter("comment", typeof(string));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_update_observation_comment_Result>("p_api_update_observation_comment", observation_comment_idParameter, observation_idParameter, commentParameter, user_emailParameter);
        }
    
        public virtual ObjectResult<p_api_update_observation_Result> p_api_update_observation(Nullable<int> observation_id, Nullable<int> indicator_id, Nullable<int> site_id, Nullable<System.DateTime> begin_date, Nullable<System.DateTime> end_date, string user_email)
        {
            var observation_idParameter = observation_id.HasValue ?
                new ObjectParameter("observation_id", observation_id) :
                new ObjectParameter("observation_id", typeof(int));
    
            var indicator_idParameter = indicator_id.HasValue ?
                new ObjectParameter("indicator_id", indicator_id) :
                new ObjectParameter("indicator_id", typeof(int));
    
            var site_idParameter = site_id.HasValue ?
                new ObjectParameter("site_id", site_id) :
                new ObjectParameter("site_id", typeof(int));
    
            var begin_dateParameter = begin_date.HasValue ?
                new ObjectParameter("begin_date", begin_date) :
                new ObjectParameter("begin_date", typeof(System.DateTime));
    
            var end_dateParameter = end_date.HasValue ?
                new ObjectParameter("end_date", end_date) :
                new ObjectParameter("end_date", typeof(System.DateTime));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_update_observation_Result>("p_api_update_observation", observation_idParameter, indicator_idParameter, site_idParameter, begin_dateParameter, end_dateParameter, user_emailParameter);
        }
    
        public virtual ObjectResult<p_api_update_observation_attachment_Result> p_api_update_observation_attachment(Nullable<int> observation_attachment_id, Nullable<int> observation_id, string attachment_file_name, byte[] attachment, string user_email)
        {
            var observation_attachment_idParameter = observation_attachment_id.HasValue ?
                new ObjectParameter("observation_attachment_id", observation_attachment_id) :
                new ObjectParameter("observation_attachment_id", typeof(int));
    
            var observation_idParameter = observation_id.HasValue ?
                new ObjectParameter("observation_id", observation_id) :
                new ObjectParameter("observation_id", typeof(int));
    
            var attachment_file_nameParameter = attachment_file_name != null ?
                new ObjectParameter("attachment_file_name", attachment_file_name) :
                new ObjectParameter("attachment_file_name", typeof(string));
    
            var attachmentParameter = attachment != null ?
                new ObjectParameter("attachment", attachment) :
                new ObjectParameter("attachment", typeof(byte[]));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_update_observation_attachment_Result>("p_api_update_observation_attachment", observation_attachment_idParameter, observation_idParameter, attachment_file_nameParameter, attachmentParameter, user_emailParameter);
        }
    
        public virtual ObjectResult<p_api_update_observation_change_Result> p_api_update_observation_change(Nullable<int> observation_change_id, Nullable<int> observation_id, string description, Nullable<System.DateTime> start_date, string user_email)
        {
            var observation_change_idParameter = observation_change_id.HasValue ?
                new ObjectParameter("observation_change_id", observation_change_id) :
                new ObjectParameter("observation_change_id", typeof(int));
    
            var observation_idParameter = observation_id.HasValue ?
                new ObjectParameter("observation_id", observation_id) :
                new ObjectParameter("observation_id", typeof(int));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var start_dateParameter = start_date.HasValue ?
                new ObjectParameter("start_date", start_date) :
                new ObjectParameter("start_date", typeof(System.DateTime));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_update_observation_change_Result>("p_api_update_observation_change", observation_change_idParameter, observation_idParameter, descriptionParameter, start_dateParameter, user_emailParameter);
        }
    
        public virtual ObjectResult<p_api_update_observation_entry_Result> p_api_update_observation_entry(Nullable<int> observation_entry_id, Nullable<int> observation_id, Nullable<int> indicator_age_range_id, string indicator_gender, Nullable<int> numerator, Nullable<int> denominator, Nullable<int> count, Nullable<decimal> rate, Nullable<bool> yes_no, string user_email)
        {
            var observation_entry_idParameter = observation_entry_id.HasValue ?
                new ObjectParameter("observation_entry_id", observation_entry_id) :
                new ObjectParameter("observation_entry_id", typeof(int));
    
            var observation_idParameter = observation_id.HasValue ?
                new ObjectParameter("observation_id", observation_id) :
                new ObjectParameter("observation_id", typeof(int));
    
            var indicator_age_range_idParameter = indicator_age_range_id.HasValue ?
                new ObjectParameter("indicator_age_range_id", indicator_age_range_id) :
                new ObjectParameter("indicator_age_range_id", typeof(int));
    
            var indicator_genderParameter = indicator_gender != null ?
                new ObjectParameter("indicator_gender", indicator_gender) :
                new ObjectParameter("indicator_gender", typeof(string));
    
            var numeratorParameter = numerator.HasValue ?
                new ObjectParameter("numerator", numerator) :
                new ObjectParameter("numerator", typeof(int));
    
            var denominatorParameter = denominator.HasValue ?
                new ObjectParameter("denominator", denominator) :
                new ObjectParameter("denominator", typeof(int));
    
            var countParameter = count.HasValue ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(int));
    
            var rateParameter = rate.HasValue ?
                new ObjectParameter("rate", rate) :
                new ObjectParameter("rate", typeof(decimal));
    
            var yes_noParameter = yes_no.HasValue ?
                new ObjectParameter("yes_no", yes_no) :
                new ObjectParameter("yes_no", typeof(bool));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_update_observation_entry_Result>("p_api_update_observation_entry", observation_entry_idParameter, observation_idParameter, indicator_age_range_idParameter, indicator_genderParameter, numeratorParameter, denominatorParameter, countParameter, rateParameter, yes_noParameter, user_emailParameter);
        }
    
        public virtual ObjectResult<p_api_get_mydata_indicators_new_Result> p_api_get_mydata_indicators_new(string user_email, Nullable<int> language_id)
        {
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var language_idParameter = language_id.HasValue ?
                new ObjectParameter("language_id", language_id) :
                new ObjectParameter("language_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_api_get_mydata_indicators_new_Result>("p_api_get_mydata_indicators_new", user_emailParameter, language_idParameter);
        }
    }
}
