//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_activity_site
    {
        public int activity_id { get; set; }
        public int site_id { get; set; }
        public string wave_fieldid { get; set; }
        public Nullable<int> coach_user_id { get; set; }
        public Nullable<System.DateTime> support_start_date { get; set; }
        public Nullable<System.DateTime> support_end_date { get; set; }
    
        public virtual t_activity activity { get; set; }
        public virtual t_site site { get; set; }
        public virtual t_fieldid wave { get; set; }
        public virtual t_user coach { get; set; }
    }
}
