//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_announcement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_announcement()
        {
            this.t_country1 = new HashSet<t_country>();
        }
    
        public int announcement_id { get; set; }
        public Nullable<byte> language_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual t_country t_country { get; set; }
        public virtual t_user t_user { get; set; }
        public virtual t_language t_language { get; set; }
        public virtual t_user t_user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_country> t_country1 { get; set; }
    }
}
