//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_chart_acceptable_number_runs
    {
        public byte points_not_on_median { get; set; }
        public Nullable<byte> runs_lower_limit { get; set; }
        public Nullable<byte> runs_upper_limit { get; set; }
    }
}
