//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_country()
        {
            this.activities = new HashSet<t_activity>();
            this.administrative_divisions = new HashSet<t_administrative_division>();
            this.announcements = new HashSet<t_announcement>();
            this.t_site = new HashSet<t_site>();
            this.user_access = new HashSet<t_user_access>();
            this.t_announcement1 = new HashSet<t_announcement>();
        }
    
        public int country_id { get; set; }
        public string name { get; set; }
        public Nullable<bool> active { get; set; }
        public string parent_site_type_fieldid { get; set; }
        public string first_level_administrative_division { get; set; }
        public string second_level_administrative_division { get; set; }
        public string third_level_administrative_division { get; set; }
        public string fourth_level_administrative_division { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_activity> activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_administrative_division> administrative_divisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_announcement> announcements { get; set; }
        public virtual t_user createdby { get; set; }
        public virtual t_fieldid parent_site_type { get; set; }
        public virtual t_user updatedby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_site> t_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_user_access> user_access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_announcement> t_announcement1 { get; set; }
    }
}
