//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_color
    {
        public int color_id { get; set; }
        public string name { get; set; }
        public string hexadecimal { get; set; }
        public byte r { get; set; }
        public byte g { get; set; }
        public byte b { get; set; }
        public Nullable<bool> active { get; set; }
    }
}
