//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_date
    {
        public System.DateTime the_date { get; set; }
        public byte the_month { get; set; }
        public short the_year { get; set; }
        public bool first_day_of_week { get; set; }
        public bool first_day_of_month { get; set; }
        public bool first_day_of_quarter { get; set; }
    }
}
