//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_note
    {
        public int note_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> activity_id { get; set; }
        public string subject { get; set; }
        public string note_text { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual t_activity activity { get; set; }
        public virtual t_user createdby { get; set; }
        public virtual t_user updatedby { get; set; }
        public virtual t_site site { get; set; }
    }
}
