//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_observation_entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_observation_entry()
        {
            this.change_history = new HashSet<t_observation_entry_change_history>();
        }
    
        public int observation_entry_id { get; set; }
        public int observation_id { get; set; }
        public Nullable<int> indicator_age_range_id { get; set; }
        public string indicator_gender { get; set; }
        public Nullable<int> numerator { get; set; }
        public Nullable<int> denominator { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<bool> yes_no { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual t_indicator_age_range age_range { get; set; }
        public virtual t_observation observation { get; set; }
        public virtual t_user createdby { get; set; }
        public virtual t_user updateby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_observation_entry_change_history> change_history { get; set; }
    }
}
