//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_observation_entry_change_history
    {
        public int change_history_id { get; set; }
        public int observation_id { get; set; }
        public int observation_entry_id { get; set; }
        public string change_type { get; set; }
        public System.DateTime change_date { get; set; }
        public int change_userid { get; set; }
        public string change_label { get; set; }
        public string change_description { get; set; }
    
        public virtual t_user change_user { get; set; }
        public virtual t_observation t_observation { get; set; }
        public virtual t_observation_entry t_observation_entry { get; set; }
    }
}
