//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_site()
        {
            this.notes = new HashSet<t_note>();
            this.user_access = new HashSet<t_user_access>();
            this.user_site = new HashSet<t_user>();
            this.user_favorite_sites = new HashSet<t_user>();
            this.observations = new HashSet<t_observation>();
            this.activities = new HashSet<t_activity_site>();
        }
    
        public int site_id { get; set; }
        public int country_id { get; set; }
        public string site_type_fieldid { get; set; }
        public int administrative_division_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string qi_index_score_fieldid { get; set; }
        public string rural_urban_fieldid { get; set; }
        public string other_key_information { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string name { get; set; }
        public string funding_type_fieldid { get; set; }
        public string partner { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual t_administrative_division administrative_division { get; set; }
        public virtual t_country country { get; set; }
        public virtual t_fieldid population_density { get; set; }
        public virtual t_fieldid site_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_note> notes { get; set; }
        public virtual t_user createdby { get; set; }
        public virtual t_user updatedby { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_user_access> user_access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_user> user_site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_user> user_favorite_sites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_observation> observations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_activity_site> activities { get; set; }
    }
}
