//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_favorite_chart
    {
        public int user_id { get; set; }
        public string chart_name { get; set; }
        public string chart_parameters { get; set; }
        public System.DateTime updated_date { get; set; }
    
        public virtual t_user t_user { get; set; }
    }
}
