//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_access
    {
        public int user_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> activity_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> administrative_division_id { get; set; }
        public bool view_access { get; set; }
        public bool update_access { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public int user_access_id { get; set; }
    
        public virtual t_activity t_activity { get; set; }
        public virtual t_administrative_division t_administrative_division { get; set; }
        public virtual t_country t_country { get; set; }
        public virtual t_site t_site { get; set; }
        public virtual t_user createdby { get; set; }
        public virtual t_user updatedby { get; set; }
        public virtual t_user user { get; set; }
    }
}
