//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_role
    {
        public int user_id { get; set; }
        public string user_role_fieldid { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    
        public virtual t_user t_user { get; set; }
        public virtual t_user t_user1 { get; set; }
        public virtual t_user t_user2 { get; set; }
    }
}
