//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_administrative_division
    {
        public Nullable<int> country_id { get; set; }
        public string country_name { get; set; }
        public int administrative_division_id { get; set; }
        public string name { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<int> level_1_id { get; set; }
        public string level_1_name { get; set; }
        public string level_1_type { get; set; }
        public Nullable<int> level_2_id { get; set; }
        public string level_2_name { get; set; }
        public string level_2_type { get; set; }
        public Nullable<int> level_3_id { get; set; }
        public string level_3_name { get; set; }
        public string level_3_type { get; set; }
        public Nullable<int> level_4_id { get; set; }
        public string level_4_name { get; set; }
        public string level_4_type { get; set; }
        public string concatenated_name { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
    }
}
