//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_site
    {
        public int site_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string country_name { get; set; }
        public string site_type_fieldid { get; set; }
        public string site_type_value { get; set; }
        public int administrative_division_id { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string qi_index_score_fieldid { get; set; }
        public string qi_index_score_value { get; set; }
        public string rural_urban_fieldid { get; set; }
        public string rural_urban_value { get; set; }
        public string other_key_information { get; set; }
        public int createdby_userid { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<int> updatedby_userid { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public string name { get; set; }
        public string partner { get; set; }
        public string funding_type_fieldid { get; set; }
        public string funding_type_value { get; set; }
        public Nullable<int> administrative_division_id_1 { get; set; }
        public string administrative_division_name_1 { get; set; }
        public string administrative_division_type_1 { get; set; }
        public Nullable<int> administrative_division_id_2 { get; set; }
        public string administrative_division_name_2 { get; set; }
        public string administrative_division_type_2 { get; set; }
        public Nullable<int> administrative_division_id_3 { get; set; }
        public string administrative_division_name_3 { get; set; }
        public string administrative_division_type_3 { get; set; }
        public Nullable<int> administrative_division_id_4 { get; set; }
        public string administrative_division_name_4 { get; set; }
        public string administrative_division_type_4 { get; set; }
        public Nullable<bool> active { get; set; }
        public string concatenated_name { get; set; }
        public string administrative_division_parent_id_1 { get; set; }
        public Nullable<int> administrative_division_parent_id_2 { get; set; }
        public Nullable<int> administrative_division_parent_id_3 { get; set; }
        public Nullable<int> administrative_division_parent_id_4 { get; set; }
    }
}
