//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_user_access
    {
        public int user_access_id { get; set; }
        public int user_id { get; set; }
        public string access_level_type { get; set; }
        public string access_level { get; set; }
        public string access_level_name { get; set; }
        public Nullable<int> country_id { get; set; }
        public string country { get; set; }
        public Nullable<int> activity_id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> administrative_division_id { get; set; }
        public bool view_access { get; set; }
        public bool update_access { get; set; }
        public string activity_name { get; set; }
        public string site_name { get; set; }
        public string country_name { get; set; }
        public string admin_div_name { get; set; }
        public string permission { get; set; }
    }
}
