//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Globalization.Chart {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IID.BusinessLayer.Globalization.Chart.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Countries.
        /// </summary>
        public static string AllCountries {
            get {
                return ResourceManager.GetString("AllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Sites.
        /// </summary>
        public static string AllSites {
            get {
                return ResourceManager.GetString("AllSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Site Types.
        /// </summary>
        public static string AllSiteTypes {
            get {
                return ResourceManager.GetString("AllSiteTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart Options.
        /// </summary>
        public static string ChartOptions {
            get {
                return ResourceManager.GetString("ChartOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Country (Indicator Report Class) Chart Options.
        /// </summary>
        public static string OptionsMultiCountry {
            get {
                return ResourceManager.GetString("OptionsMultiCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data points to apply run chart rules.
        /// </summary>
        public static string RuleNotEnoughPoints {
            get {
                return ResourceManager.GetString("RuleNotEnoughPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too few or too many runs.
        /// </summary>
        public static string RuleRuns {
            get {
                return ResourceManager.GetString("RuleRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutive points above or below median.
        /// </summary>
        public static string RuleShift {
            get {
                return ResourceManager.GetString("RuleShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule(s) triggered.
        /// </summary>
        public static string RulesTriggered {
            get {
                return ResourceManager.GetString("RulesTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consecutive points going up or down.
        /// </summary>
        public static string RuleTrend {
            get {
                return ResourceManager.GetString("RuleTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run chart rules.
        /// </summary>
        public static string RunChartRules {
            get {
                return ResourceManager.GetString("RunChartRules", resourceCulture);
            }
        }
    }
}
