//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Globalization.Activity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IID.BusinessLayer.Globalization.Activity.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Search.
        /// </summary>
        public static string ActivitySearch {
            get {
                return ResourceManager.GetString("ActivitySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Manager(s).
        /// </summary>
        public static string AdditionalManagers {
            get {
                return ResourceManager.GetString("AdditionalManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funder.
        /// </summary>
        public static string Funder {
            get {
                return ResourceManager.GetString("Funder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Key Information.
        /// </summary>
        public static string OtherKeyInformation {
            get {
                return ResourceManager.GetString("OtherKeyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Manager.
        /// </summary>
        public static string PrimaryManager {
            get {
                return ResourceManager.GetString("PrimaryManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank By Improvement.
        /// </summary>
        public static string RankByImprovement {
            get {
                return ResourceManager.GetString("RankByImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string StatusActive {
            get {
                return ResourceManager.GetString("StatusActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string StatusAll {
            get {
                return ResourceManager.GetString("StatusAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string StatusCompleted {
            get {
                return ResourceManager.GetString("StatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Area.
        /// </summary>
        public static string TechnicalArea {
            get {
                return ResourceManager.GetString("TechnicalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Areas.
        /// </summary>
        public static string TechnicalAreas {
            get {
                return ResourceManager.GetString("TechnicalAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Area Sub-Type.
        /// </summary>
        public static string TechnicalAreaSubtype {
            get {
                return ResourceManager.GetString("TechnicalAreaSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Area Sub-Types.
        /// </summary>
        public static string TechnicalAreaSubtypes {
            get {
                return ResourceManager.GetString("TechnicalAreaSubtypes", resourceCulture);
            }
        }
    }
}
