//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Globalization.Indicator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IID.BusinessLayer.Globalization.Indicator.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Indicator.
        /// </summary>
        public static string AddIndicator {
            get {
                return ResourceManager.GetString("AddIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Categories.
        /// </summary>
        public static string AgeRanges {
            get {
                return ResourceManager.GetString("AgeRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert message range.
        /// </summary>
        public static string ChangeVariable {
            get {
                return ResourceManager.GetString("ChangeVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collection Frequency.
        /// </summary>
        public static string DataCollectionFrequency {
            get {
                return ResourceManager.GetString("DataCollectionFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string Decrease {
            get {
                return ResourceManager.GetString("Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definition.
        /// </summary>
        public static string Definition {
            get {
                return ResourceManager.GetString("Definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denominator.
        /// </summary>
        public static string Denominator {
            get {
                return ResourceManager.GetString("Denominator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Other Categories.
        /// </summary>
        public static string DisaggregateByAge {
            get {
                return ResourceManager.GetString("DisaggregateByAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Sex.
        /// </summary>
        public static string DisaggregateBySex {
            get {
                return ResourceManager.GetString("DisaggregateBySex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Sex, Age.
        /// </summary>
        public static string DisaggregateBySexAge {
            get {
                return ResourceManager.GetString("DisaggregateBySexAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string DisaggregateNone {
            get {
                return ResourceManager.GetString("DisaggregateNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disaggregation.
        /// </summary>
        public static string Disaggregation {
            get {
                return ResourceManager.GetString("Disaggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string Increase {
            get {
                return ResourceManager.GetString("Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s considered good?.
        /// </summary>
        public static string IncreaseIsGood {
            get {
                return ResourceManager.GetString("IncreaseIsGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerator.
        /// </summary>
        public static string Numerator {
            get {
                return ResourceManager.GetString("Numerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per.
        /// </summary>
        public static string RatePer {
            get {
                return ResourceManager.GetString("RatePer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Class.
        /// </summary>
        public static string ReportClass {
            get {
                return ResourceManager.GetString("ReportClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling.
        /// </summary>
        public static string Sampling {
            get {
                return ResourceManager.GetString("Sampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Performance.
        /// </summary>
        public static string TargetPerformance {
            get {
                return ResourceManager.GetString("TargetPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for Good Performance.
        /// </summary>
        public static string ThresholdGoodPerformance {
            get {
                return ResourceManager.GetString("ThresholdGoodPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threshold for Poor Performance.
        /// </summary>
        public static string ThresholdPoorPerformance {
            get {
                return ResourceManager.GetString("ThresholdPoorPerformance", resourceCulture);
            }
        }
    }
}
