//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Globalization.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IID.BusinessLayer.Globalization.Home.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Activities.
        /// </summary>
        public static string AssignedActivities {
            get {
                return ResourceManager.GetString("AssignedActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Countries.
        /// </summary>
        public static string AssignedCountries {
            get {
                return ResourceManager.GetString("AssignedCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Sites.
        /// </summary>
        public static string AssignedSites {
            get {
                return ResourceManager.GetString("AssignedSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Director Report.
        /// </summary>
        public static string CountryDirectorReport {
            get {
                return ResourceManager.GetString("CountryDirectorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 Days.
        /// </summary>
        public static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations Last 7 Days.
        /// </summary>
        public static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Activities.
        /// </summary>
        public static string MyActivities {
            get {
                return ResourceManager.GetString("MyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Charts.
        /// </summary>
        public static string MyCharts {
            get {
                return ResourceManager.GetString("MyCharts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorites.
        /// </summary>
        public static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Sites.
        /// </summary>
        public static string MySites {
            get {
                return ResourceManager.GetString("MySites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total .
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the USAID ASSIST Project&apos;s Improvement Indicator Database (IID).
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
