//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IID.BusinessLayer.Globalization.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IID.BusinessLayer.Globalization.Email.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}
        ///
        ///We received a password change request for your account.  
        ///If you made this request, &lt;a href=&quot;{2}&quot; target=&quot;_blank&quot;&gt;click here&lt;/a&gt; to start the reset process.
        ///
        ///If you did not request this change, please &lt;a href=&quot;{3}&quot; target=&quot;_blank&quot;&gt;contact the system administrator&lt;/a&gt; immediately.
        ///
        ///Thank you
        ///
        ///The Improvement Indicator Database Team
        ///{4}.
        /// </summary>
        public static string ForgotPasswordBody {
            get {
                return ResourceManager.GetString("ForgotPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID Password Change Request.
        /// </summary>
        public static string ForgotPasswordSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}
        ///
        ///Your request has been submitted for approval.  You will be notified via email once your request is approved/denied.  If you have any questions, please &lt;a href=&quot;{2}&quot; target=&quot;_blank&quot;&gt;contact the USAID system administrator&lt;/a&gt;.
        ///
        ///Thank you
        ///
        ///The Improvement Indicator Database Team
        ///{3}.
        /// </summary>
        public static string NewRequestSubmittedBody {
            get {
                return ResourceManager.GetString("NewRequestSubmittedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID New Request Submitted for Approval.
        /// </summary>
        public static string NewRequestSubmittedSubject {
            get {
                return ResourceManager.GetString("NewRequestSubmittedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}
        ///
        ///Your password was recently updated.
        ///
        ///If you did not request this change, please &lt;a href=&quot;{2}&quot; target=&quot;_blank&quot;&gt;contact the system administrator&lt;/a&gt; immediately.
        ///
        ///Thank you
        ///
        ///The USAID Team
        ///{3}.
        /// </summary>
        public static string PasswordChangedBody {
            get {
                return ResourceManager.GetString("PasswordChangedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID Password Change Confirmation.
        /// </summary>
        public static string PasswordChangedSubject {
            get {
                return ResourceManager.GetString("PasswordChangedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a reminder that a request for {0}  is still pending your approval.  &lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Click here&lt;/a&gt; to view the request.
        ///
        ///Thank you
        ///
        ///The Improvement Indicator Database Team.
        /// </summary>
        public static string RequestApprovalReminderBody {
            get {
                return ResourceManager.GetString("RequestApprovalReminderBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID Request Approval Required Reminder.
        /// </summary>
        public static string RequestApprovalReminderSubject {
            get {
                return ResourceManager.GetString("RequestApprovalReminderSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new request for {0} has been submitted that requires your approval.  &lt;a href=&quot;{1}&quot; target=&quot;_blank&quot;&gt;Click here&lt;/a&gt; to view the request.
        ///
        ///Thank you.
        /// </summary>
        public static string RequestApprovalRequiredBody {
            get {
                return ResourceManager.GetString("RequestApprovalRequiredBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID Request Approval Required.
        /// </summary>
        public static string RequestApprovalRequiredSubject {
            get {
                return ResourceManager.GetString("RequestApprovalRequiredSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}
        ///
        ///Your request for {2} has been approved.
        ///
        ///Thank you
        ///
        ///The USAID Team
        ///{3}.
        /// </summary>
        public static string RequestApprovedBody {
            get {
                return ResourceManager.GetString("RequestApprovedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID Request Approved.
        /// </summary>
        public static string RequestApprovedSubject {
            get {
                return ResourceManager.GetString("RequestApprovedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}
        ///
        ///Your request for {2} has been denied for the following reasons:
        ///&lt;blockquote&gt;{3}&lt;/blockquote&gt;
        ///
        ///Thank you
        ///
        ///The USAID Team
        ///{4}.
        /// </summary>
        public static string RequestDeniedBody {
            get {
                return ResourceManager.GetString("RequestDeniedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IID Request Denied.
        /// </summary>
        public static string RequestDeniedSubject {
            get {
                return ResourceManager.GetString("RequestDeniedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0} {1}
        ///
        ///Welcome to the USAID application.  Your account has been activated.  
        ///
        ///&lt;a href=&quot;{2}&quot; target=&quot;_blank&quot;&gt;Click here&lt;/a&gt; to change your password.
        ///
        ///If you have any questions, please &lt;a href=&quot;{3}&quot; target=&quot;_blank&quot;&gt;contact the system administrator&lt;/a&gt;.
        ///
        ///Thank you
        ///
        ///The USAID Team
        ///{4}.
        /// </summary>
        public static string WelcomeBody {
            get {
                return ResourceManager.GetString("WelcomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Improvement Indicator Database (IID).
        /// </summary>
        public static string WelcomeSubject {
            get {
                return ResourceManager.GetString("WelcomeSubject", resourceCulture);
            }
        }
    }
}
